name: Build and deploy

on:
  workflow_dispatch:
    inputs:
      env:
        description: Environment to deploy to
        required: true
        type: environment

permissions:
  contents: read
  id-token: write

jobs:
  build:
    name: Lint, format, test and build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout ðŸ›Žï¸
        uses: actions/checkout@v4

      - uses: pnpm/action-setup@v2

      - name: Use Node LTS âœ¨
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: pnpm

      - name: Install dependencies ðŸ“¦ï¸
        run: pnpm install --frozen-lockfile

      - name: Build ðŸ”¨
        run: pnpm build

      - name: Upload built website ðŸ“¦ï¸
        uses: actions/upload-artifact@v4
        with:
          name: website
          path: ./dist

  deploy:
    name: Deployment
    runs-on: ubuntu-latest
    needs: build
    concurrency:
      group: "Deploy to ${inputs.environment}"
    environment:
      name: "${inputs.environment}"

    steps:
      - name: Download built website ðŸ“¦
        uses: actions/upload-artifact@v4
        with:
          name: website
          path: ./website

      - id: list-working-directory
        name: List working directory
        run: ls -la

      - id: list-website
        name: List website
        run: ls -la ./website

      - id: auth
        name: Authenticate to Google Cloud ðŸ”
        uses: google-github-actions/auth@v2
        with:
          workload_identity_provider: projects/184284737035/locations/global/workloadIdentityPools/marketing-website/providers/marketing-website-github-actions

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@v2
        with:
          version: ">= 502.0.0"

      - name: "Use gcloud CLI"
        run: "gcloud info"
